import Head from "next/head";
import { Layout } from "../layout/Layout";
import { Main } from "../components/main/Main";

export interface IVideo {
  embed: string;
  text: string;
  link: string;
}

export interface IUser {
  name: string;
  photo: string;
  online: boolean;
  registration: string;
  age: number;
}

export type IData = {
  data: {
    video: IVideo;
    users: IUser[];
  };
};

export default function Home({ data }: IData) {
  return (
    <>
      <Head>
        <title>Embed</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Cairo:wght@400;600;700&family=Poppins:wght@400;600&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Layout>
        <Main data={data} />
      </Layout>
    </>
  );
}

export async function getServerSideProps() {
  const res = await fetch("https://tz.smart-ui.pro/");
  const data = await res.json();

  return { props: { data } };
}
